### ISSUE TITLE
library broken when importing directly as opposed to running from commandline

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/nocap#11]
The addition of the command line functionality broke the library import functionality. Running for ex: `nocap -o .....` on the commandline works, but importing:
 ```
 import lil_nocap as nc
 ...
 nc.start()
 ```
 won't work. 
 
This has been broken as of https://github.com/harvard-lil/nocap/commit/02dca3ca968a54d20cb37cac71bb0b66e7f4e43b the library has been broken

**Comment by bensteinberg** [comment]
I think you can run
```
from lil_nocap.nocap import NoCap as nc
nc.start('opinions_file', 'opinion_clusters_file', 'courts_file', 'dockets_file', 'citation_file')
```

**Comment by sabzo** [comment]
@bensteinberg 
I think your code has given me a good place to start! There's one issue and I think it's because the constructor that returns an object to `nc` hasn't been called, and leading to this error:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/2899124/228863176-11f781f8-b533-439e-aa93-9af6a5bf175a.png">

**Comment by sabzo** [comment]
done
