### ISSUE TITLE
Converting Opinion cluster CSV into a Dict causes error

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/nocap#15]
When converting opinion_cluster to csv (6.7GB) results in the following error:
```
field larger than field limit (131072)
```

```
Error                                     Traceback (most recent call last)
File <timed exec>:1

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lil_nocap/__init__.py:34, in NoCap.__init__(self, opinions_fn, opinion_clusters_fn, courts_fn, dockets_fn, citation_fn)
     32 # if memory is < 32 GB use Dask for large files, otherwise use dicts
     33 self._df_dockets = self.get_pickled_docket() #self.init_dockets_dict() # self.init_dockets_df()
---> 34 self._df_opinion_clusters = self.init_opinion_clusters_dict() #self.init_opinion_clusters_df()
     35 self._df_courts = self.init_courts_df()
     36 self._df_citation = self.init_citation_df()

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lil_nocap/__init__.py:161, in NoCap.init_opinion_clusters_dict(self, fn)
    159 with open(fn) as oc:
    160     reader = csv.DictReader(oc)
--> 161     for row in reader:
    162         self._cluster_dict[int(row['id'])] = row['judges'], row['docket_id'], row['case_name'], row['case_name_full']
    163 end = time.perf_counter()

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/csv.py:111, in DictReader.__next__(self)
    108 if self.line_num == 0:
    109     # Used only for its side effect.
    110     self.fieldnames
--> 111 row = next(self.reader)
    112 self.line_num = self.reader.line_num
    114 # unlike the basic reader, we prefer not to return blanks,
    115 # because we will typically wind up with a dict full of None
    116 # values

Error: field larger than field limit (131072)
```

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/2899124/234080625-8baab3dc-c8ed-4994-af6b-2345dfa0023b.png">

**Comment by sabzo** [comment]
Note: 
When adding a `try/except` conversion happens, however some rows are left out... exploring the format of the rows that's causing the failure..

**Comment by sabzo** [comment]
related to https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

Might indicate bad data in csv, particularly row that begins with id `5098574` is malformatted -- the `head_notes` spans across several new lines. Instead of each line being treated like a record with the expected number of columns, the next lines are vary in amount of fields.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/2899124/234094904-32e838d8-f4b5-406d-854a-ea1e357e6089.png">


## Commas in text of row with id 5098574: improperly treated as fields:
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/2899124/234095742-709e6954-42d9-4a96-b208-4cc7b61430c8.png">

**Comment by sabzo** [comment]
1. Lines where the entire row is `Statement` are malformatted, over 2000 lines

When reading csv using pandas:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/2899124/234098487-66e57709-ce9f-493f-9299-c3e8674ac2cb.png">

**Comment by sabzo** [comment]
When redownloading https://storage.courtlistener.com/bulk-data/opinion-clusters-2022-12-31.csv.bz2 and importing  csv as a dataframe the issue disappears -- somewhere somehow the original file must've become corrupted on my local machine 👎🏿  :/ 

### second attempt (update)

Somehow pandas reads csv without failing, despite improperly formed columns (differing amount of fields in each row)

For example there are `126159` rows  (using reg ex: `^<`) where all the text in the row are not the  expected field values and have unexpected number of fields for ex:

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/2899124/234103849-5e4e6bf4-e50d-4110-b4cf-4ab8d8fe27bc.png">

^^ this happens despite downloading a fresh copy of https://storage.courtlistener.com/bulk-data/opinion-clusters-2022-12-31.csv.bz2

## When comparing number of lines in file vs number of lines when panda imports csv:

`wc -l opinion-clusters-2022-12-31.csv` = 12,779,903
```
df = pd.read_csv(opinion_clusters_fn)
len(df)
```
Pandas shows `8,894,488` lines.

Almost 4 million lines are skipped without error...

## verdict

So apparently pandas intelligently reads the new lines, whereas `vim` and python's native `csv.DictReader` fails to distinguish the new line character and ends up treating regular commas as delimiters. This also means converting the csv into a `dict` also fails... (yay pandas?)

for ex pandas reads newlines properly: 
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/2899124/234111824-d7272b12-673f-4a65-9b24-945a21b40cb1.png">

**Comment by sabzo** [comment]
Moving this to `Done` because it's impossible to convert https://storage.courtlistener.com/bulk-data/opinion-clusters-2022-12-31.csv.bz2 into a dict. Converting into a dict would've allowed for faster lookup times than what pandas offers...

**Comment by sabzo** [comment]
Reopening issue because https://datascience.stackexchange.com/questions/35868/how-to-store-strings-in-csv-with-new-line-characters might solve it cc @mdellabitta

**Comment by jdcc** [comment]
I hit this as well. I think the issue is just that some of the fields are really, really long. I threw this: `csv.field_size_limit(1_000_000)` at the top of the file and it imported everything.

**Comment by sabzo** [comment]
solved by using pandas
